version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - 3000:80
    volumes:
      - .:/app
    depends_on:
      - mongo
    command: yarn start:prod

  mongo:
    build: ./mongodb_replica
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mongo
      MONGO_REPLICA_HOST: host.docker.internal
      MONGO_REPLICA_PORT: 27017
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017?authSource=admin&directConnection=true
